# .streamlit/secrets.toml

[openai]
OPENAI_API_KEY = "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"


[connections.snowflake]
account = "KECHPQY-ARB81606"
user = "diwakarnahata4aws"
password = "Info@999"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
# database = "DFS"
# schema = "DEMO"
# table = "STG_INVOICES"

