# .streamlit/secrets.toml

[openai]
OPENAI_API_KEY = "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"


[connections.snowflake]
snowflake_account = "KECHPQY-ARB81606"
snowflake_user = "diwakarnahata4aws"
snowflake_password = "Info@999"
snowflake_warehouse = "COMPUTE_WH"
snowflake_role = "ACCOUNTADMIN"
snowflake_database = "DFS"
snowflake_schema = "DEMO"
snowflake_table = "STG_INVOICES"

