# .streamlit/secrets.toml

OPENAI_API_KEY = "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"


[connections.snowflake]
snowflake_account = "KECHPQY-ARB81606"
snowflake_user = "diwakarnahata4aws"
snowflake_password = "Info@999"
snowflake_warehouse = "COMPUTE_WH"
snowflake_role = "ACCOUNTADMIN"
snowflake_database = "DFS"
snowflake_schema = "DEMO"
snowflake_table = "STG_INVOICES"

