# .streamlit/secrets.toml

[openai]
OPENAI_API_KEY = ""


[connections.snowflake]
account = ""
user = ""
password = ""
warehouse = "H"
role = "ACCOUNTADMIN"
database = "DFS"
schema = "DEMO"
# table = "STG_INVOICES"

