# .streamlit/secrets.toml

# [openai]
# OPENAI_API_KEY = ""


[connections.snowflake]
account = "kechpqy-arb81606"
user = "diwakarnahata4aws"
password = "Info@999"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
database = "DFS"
schema = "DEMO"
# table = "STG_INVOICES"

